Problem: compile failure on Postgres master
```
error: use of undeclared identifier 'T_UpperUniquePath'; did you mean 'T_UniquePath'?
```

Solution: remove `UpperUniquePath` for Postgres 19

Relevant change in Postgres: https://github.com/postgres/postgres/commit/24225ad9aafc576295e210026d8ffa9f50d61145