Problem: `dngettext` error
Some systems fail to compile with:

```
error: expected ')'
   67 | extern char *dngettext (const char *__domainname, const char *__msgid1,
```

Solution: ensure we load PFR before Postgres

This error is caused by a macro collision. PostgreSQL’s server header
(c.h) defines a macro named dngettext. Later, when a system header like
/usr/include/libintl.h is included (directly or indirectly via <locale>
or <iomanip>), it expects to see a function declaration for dngettext.

But because the macro is active, the function prototype gets mangled by
the macro expansion, resulting in syntax errors like “expected
unqualified-id” or mismatched parentheses.